name: build & push docker container

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tags to publish'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: metal
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/hibobmaster/elk
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: ghcr.io/hibobmaster/elk:latest,ghcr.io/hibobmaster/elk:${{ github.event.inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
